// awk programs run through gawk (LC_ALL=C) and through text/Awk, comparing
// stdout and the exit status. `in` is stdin (absent means none), `args` goes
// before the program, `ops` after it, and `files` are readable by name.
// Kept to what POSIX awks agree on, or where gawk is the chosen reading: no
// rand() values, no for-in over several keys (every awk orders those its own
// way), no octal source constants, no gawk-only functions.
const table = 'alice 30 NY\nbob 25 LA\ncarol 35 NY\ndave 40 SF\n';
const csv = 'id,name,score\n1,ann,90\n2,ben,\n3,,75\n';

export default [
  // Fields, FS and OFS
  { p: '{ print $2 }', in: table },
  { p: '{ print $NF, $(NF-1) }', in: table },
  { p: '{ print NF }', in: 'a b  c\n\n   \n x \n' },
  { p: '{ print $1 }', in: '  lead trail  \n' },
  { args: ['-F', ','], p: '{ print $2 "|" $3 "|" NF }', in: csv },
  { args: ['-F', ':'], p: '{ print $1, $NF }', in: 'root:x:0:0:root:/root:/bin/bash\n' },
  { args: ['-F', '\\t'], p: '{ print $2 }', in: 'a\tb c\td\n' },
  { args: ['-F', 't'], p: '{ print $2 }', in: 'a\tb\n' },
  { args: ['-F', '[,;]'], p: '{ print $1 "-" $2 "-" $3 }', in: 'a,b;c\n' },
  { args: ['-F', ', *'], p: '{ print $2 }', in: 'x,   y, z\n' },
  { args: ['-F', '|'], p: '{ print $2 }', in: 'a|b|c\n' },
  { args: ['-F', '.'], p: '{ print $2 }', in: 'a.b.c\n' },
  { p: 'BEGIN { FS = "" } { print $1, $3, NF }', in: 'abc\n' },
  { p: 'BEGIN { FS = "[ ]" } { print NF, "[" $1 "]" }', in: ' a  b\n' },
  { p: 'BEGIN { OFS = "-" } { $1 = $1; print }', in: 'a b c\n' },
  { p: 'BEGIN { OFS = "-" } { print; print $1, $2 }', in: 'a b c\n' },
  { p: '{ $3 = "X"; print; print NF }', in: 'a b\n' },
  { p: '{ $2 = ""; print; print NF }', in: 'a b c\n' },
  { p: '{ NF = 2; print; NF = 4; print; print NF }', in: 'a b c\n' },
  { p: '{ $0 = "x y z"; print $2, NF }', in: 'a\n' },
  { p: '{ FS = ":" } { print $1 }', in: 'a:b c\nd:e f\n' },
  { p: '{ FS = ":"; $0 = $0; print $1 }', in: 'a:b c\n' },
  { p: '{ $1 = $1 } 1', in: '  a   b  \n' },
  { p: '{ print $(1+1) }', in: 'a b c\n' },
  { p: '{ i = 1; print $i++; print i }', in: 'a b\n' },
  { p: '{ print $NF-1 }', in: '1 2 10\n' },
  { p: '{ print $5 == "", $5 == 0, length($5) }', in: 'a\n' },

  // Records and RS
  { p: 'END { print NR }', in: 'a\nb\nc' },
  { p: 'END { print NR }', in: '' },
  { p: '{ print NR ": " $0 }', in: 'a\n\nb\n' },
  { p: 'BEGIN { RS = "" } { print NR ": " $1 "/" $NF "/" NF }', in: '\n\na b\nc\n\n\n\nd e\n\n' },
  { p: 'BEGIN { RS = ""; FS = ":" } { print $1 "|" $2 "|" NF }', in: 'a:b\nc:d\n\ne\n' },
  { p: 'BEGIN { RS = ";" } { print NR "[" $0 "]" }', in: 'a;b;c' },
  { p: 'BEGIN { RS = "--+" } { print NR "[" $0 "]" }', in: 'a--b---c\n' },
  { p: 'BEGIN { ORS = "|" } { print }', in: 'a\nb\n' },
  { p: 'END { print $0, NF }', in: 'first\nlast one\n' },
  { p: '{ print FNR, NR }', ops: ['f1', 'f2'], files: { f1: 'a\nb\n', f2: 'c\n' } },
  { p: 'FNR == 1 { print FILENAME }', ops: ['f1', 'f2'], files: { f1: 'a\n', f2: 'b\n' } },
  { p: 'FNR == 1 { nextfile } { print }', ops: ['f1', 'f2'], files: { f1: 'a\nb\n', f2: 'c\nd\n' } },
  { p: '{ print }', ops: ['f1', '-', 'f2'], in: 'stdin\n', files: { f1: 'one\n', f2: 'two\n' } },
  { p: '{ print x, $0 }', ops: ['x=1', 'f1', 'x=2', 'f1'], files: { f1: 'l\n' } },
  { p: 'BEGIN { ARGV[1] = "" } { print }', ops: ['f1', 'f2'], files: { f1: 'no\n', f2: 'yes\n' } },
  { p: 'BEGIN { ARGV[ARGC++] = "f2" } { print }', ops: ['f1'], files: { f1: 'a\n', f2: 'b\n' } },
  { p: 'BEGIN { print ARGC, ARGV[0], ARGV[1], ARGV[2] }', ops: ['one', 'two'] },

  // Patterns
  { p: '/NY/', in: table },
  { p: '!/NY/ { print $1 }', in: table },
  { p: '$2 > 28', in: table },
  { p: '$2 >= 30 && $3 == "NY" { print $1 }', in: table },
  { p: 'NR == 2, NR == 3 { print NR }', in: table },
  { p: '/bob/, /carol/', in: table },
  { p: '/a/, /a/ { print NR }', in: 'a\nb\na\n' },
  { p: '$1 ~ /^[ab]/', in: table },
  { p: '$3 !~ "Y$"', in: table },
  { p: 'NR % 2', in: '1\n2\n3\n4\n5\n' },
  { p: 'length > 3', in: 'ab\nabcd\nabc\nabcde\n' },
  { p: '!seen[$0]++', in: 'x\ny\nx\nz\ny\n' },
  { p: 'END { }', in: 'a\n' },
  { p: 'BEGIN { print "only" }', in: 'never read\n' },
  { p: '1; { print "again" }', in: 'a\n' },
  { p: '$0', in: '0\n1\n\n0.0\nx\n' },

  // Numbers, strings, comparison
  { p: 'BEGIN { print 1 " " -1 }' },
  { p: 'BEGIN { print 1+2 "3", 2*3 4 }' },
  { p: 'BEGIN { print -2^2, 2^3^2, 2**10, 2^-1 }' },
  { p: 'BEGIN { print 7%3, -7%3, 7%-3, 5.5%2 }' },
  { p: 'BEGIN { print 1e6, 1e-5, 123456.7, 1234567.8, 0.1+0.2, 1/3, 100/3 }' },
  { p: 'BEGIN { print 2^53, 2^53+1, 2^70, 1e20, -1e20, 123456789012 }' },
  { p: 'BEGIN { print -0, 0*-1, -0.0 }' },
  { p: 'BEGIN { print 0x10, 0X1f }' },
  { p: 'BEGIN { OFMT = "%.2f"; x = 3.14159; print x; print x "" }' },
  { p: 'BEGIN { CONVFMT = "%.2g"; x = 3.14159; print x; y = x ""; print y; a[x] = 1; for (k in a) print k }' },
  { p: 'BEGIN { CONVFMT = "%d"; a = 3.9; print (a "") }' },
  { p: 'BEGIN { x = "3.0"; y = 3; print (x == y), (x+0 == y) }' },
  { p: 'BEGIN { print ("10" < "9"), (10 < 9), ("abc" < "abd"), ("" < "a"), ("A" < "a") }' },
  { p: '{ print ($1 < $2), ($1 == $3) }', in: '2 10 2.0\n' },
  { p: '{ print ($1 == 10), length($1) }', args: ['-F', ','], in: ' 10 ,x\n' },
  { p: '{ print ($1 == 26), $1 + 0, ($1 < 1) }', in: '0x1A\n' },
  { p: '{ print ($1 == 1000), ($2 == 0.5), ($3 == 3), ($4 > 1) }', in: '1e3 .5 +3 abc\n' },
  { p: '{ print !$1, !$0, ($1 == "0"), ($1 == 0) }', in: '0\n' },
  { p: 'BEGIN { print -"3", +"4x", !"0", !"", !0, !"a" }' },
  { p: 'BEGIN { x; print (x == 0), (x == ""), length(x), x + 0, "[" x "]" }' },
  { p: 'BEGIN { x = "x"; x++; print x; y = "5z"; y += 1; print y }' },
  { p: 'BEGIN { a = "10"; b = 9; print (a < b); c = a + 0; print (c < b) }' },
  { p: 'BEGIN { print 1 == 1.0, (1 < 2) (3 < 4), 3 " " 4 }' },
  { p: 'BEGIN { print length(12345), length(1/4), length() }' },
  { p: 'BEGIN { n = 5; print n " items"; print n+1 "x" }' },
  { p: 'BEGIN { print 1 > 2 ? "yes" : "no" }' },
  { p: 'BEGIN { print (1 > 2) ? "yes" : "no" }' },
  { p: 'BEGIN { x = y = 3; x += y *= 2; print x, y }' },
  { p: 'BEGIN { i = 5; print i++ + ++i, i--, --i, i }' },
  { p: 'BEGIN { x = 10; x /= 4; print x; x ^= 2; print x; x %= 4; print x; x -= 1; print x }' },
  { p: 'BEGIN { print 1 < 2 < 3 }' },
  { p: 'BEGIN { s = "a" "b" "c"; print s, length(s) }' },
  { p: 'BEGIN { print "a" > "/dev/stdout"; print "b" }' },

  // printf and sprintf
  { p: 'BEGIN { printf "%d|%i|%5d|%-5d|%05d|%+d|% d\\n", 42.9, -42.9, 42, 42, 42, 5, 5 }' },
  { p: 'BEGIN { printf "%x|%X|%o|%u|%#x|%#o\\n", 255, 255, 8, 3000000000, 255, 8 }' },
  { p: 'BEGIN { printf "%x|%u|%o\\n", -1, -1, -1 }' },
  { p: 'BEGIN { printf "%f|%.2f|%8.3f|%-8.1f|%e|%.3E|%g|%G\\n", 3.14159, 3.14159, 3.14159, 3.14159, 12345.678, 0.000123, 0.0001, 1e-10 }' },
  { p: 'BEGIN { printf "%s|%10s|%-10s|%.2s|%5.1s|\\n", "hello", "hi", "hi", "hello", "xyz" }' },
  { p: 'BEGIN { printf "%c%c%c|%5c|%-3c|\\n", 72, "i!", 33.9, "x", "y" }' },
  { p: '{ printf "%c|%c\\n", $1, $2 }', in: '65 x\n' },
  { p: 'BEGIN { printf "%*d|%-*d|%.*f|%*s|\\n", 5, 42, 4, 7, 2, 3.14159, -4, "ab" }' },
  { p: 'BEGIN { printf "%d %d %s\\n", "0x1A", " 12 ", 1e6 }' },
  { p: 'BEGIN { printf "%d|%d\\n", 1e20, -1e20 }' },
  { p: 'BEGIN { printf "%.3d|%5.3d|%-6.2x|\\n", 7, 7, 10 }' },
  { p: 'BEGIN { printf "100%%\\n"; printf "%5%|\\n" }' },
  { p: 'BEGIN { printf "no newline" }' },
  { p: 'BEGIN { printf("%s-%s\\n", "a", "b") }' },
  { p: 'BEGIN { x = sprintf("%05.1f|%s", 2.25, "t"); print x, length(x) }' },
  { p: 'BEGIN { printf "%s %s\\n", "only" }' },
  { p: 'BEGIN { printf "%s\\n", 3.14159265; printf "%d\\n", "abc" }' },
  { p: 'BEGIN { printf "%5.1e|%g|%g|%g\\n", 12345, 123456789, 0.00001234, 100 }' },

  // Builtins
  { p: 'BEGIN { print substr("hello", 2), substr("hello", 2, 3), substr("hello", 0), substr("hello", -1, 3) }' },
  { p: 'BEGIN { print substr("hello", 1.5), substr("hello", 1.5, 2.3), substr("hello", 5, 10) "|" substr("hello", 6) "|" substr("", 1) "|" substr("hi", 1, 0) "|" }' },
  { p: 'BEGIN { print index("hello", "ll"), index("hello", "z"), index("abc", ""), index("", "") }' },
  { p: 'BEGIN { print length("abc"), length(""), length(123) }' },
  { p: '{ print length }', in: 'abc\n\nhello\n' },
  { p: 'BEGIN { n = split("a:b:c", p, ":"); print n, p[1], p[3] }' },
  { p: 'BEGIN { n = split("  a  b  ", p); print n, "[" p[1] "]", "[" p[2] "]" }' },
  { p: 'BEGIN { n = split("a1b22c", p, /[0-9]+/); print n, p[1], p[2], p[3] }' },
  { p: 'BEGIN { n = split("abc", p, ""); print n, p[1], p[3] }' },
  { p: 'BEGIN { n = split("", p); print n, length(p) }' },
  { p: 'BEGIN { n = split("a,b,", p, ","); print n, "[" p[3] "]" }' },
  { p: 'BEGIN { split("x y", p); p[5] = 1; n = split("q", p); print n, length(p), (5 in p) }' },
  { p: 'BEGIN { split("3 10 2", p); print (p[1] < p[2]) }' },
  { p: 'BEGIN { s = "hello world"; n = sub(/o/, "0", s); print n, s; n = gsub(/o/, "0", s); print n, s }' },
  { p: 'BEGIN { s = "aaa"; n = gsub(/a/, "\\\\&-&", s); print n, s }' },
  { p: 'BEGIN { s = "hello"; sub(/l+/, "[&]", s); print s }' },
  { p: 'BEGIN { s = "a.b.c"; gsub(".", "x", s); print s; t = "a.b.c"; gsub(/\\./, "-", t); print t }' },
  { p: 'BEGIN { s = "abc"; gsub("", "-", s); print s; t = "abc"; n = gsub(/b*/, "-", t); print n, t }' },
  { p: 'BEGIN { s = "foo"; gsub(/o/, "\\\\\\\\", s); print s }' },
  { p: 'BEGIN { s = "aaa"; gsub(/^a/, "b", s); print s; t = "abc"; gsub(/$/, "!", t); print t }' },
  // The replacement's backslashes, as the awk source spells them (String.raw: no JS escaping).
  { p: String.raw`BEGIN { t = "x"; gsub(/x/, "[\\&]", t); print t }` },
  { p: String.raw`BEGIN { t = "x"; gsub(/x/, "[\\\\&]", t); print t }` },
  { p: String.raw`BEGIN { t = "x"; gsub(/x/, "[\\\\\\&]", t); print t }` },
  { p: String.raw`BEGIN { t = "x"; gsub(/x/, "[\\\\\\\\]", t); print t }` },
  { p: String.raw`BEGIN { t = "x"; gsub(/x/, "[\\q\\\\q]", t); print t }` },
  { p: 'BEGIN { s = "x"; n = gsub(/y/, "z", s); print n, s }' },
  { p: '{ gsub(/a/, "A"); print; print NF }', in: 'a b a\n' },
  { p: '{ sub(/b/, "B B", $2); print; print NF, $2 }', in: 'a b c\n' },
  { p: 'BEGIN { print match("foobar", /o+/), RSTART, RLENGTH; print match("x", /z/), RSTART, RLENGTH }' },
  { p: 'BEGIN { if (match("key=value", "=")) print substr("key=value", 1, RSTART - 1) }' },
  { p: 'BEGIN { print toupper("abc1"), tolower("ABC1") }' },
  { p: 'BEGIN { print int(3.9), int(-3.9), int("4.5x"), int("x") }' },
  { p: 'BEGIN { printf "%.4f %.4f %.4f %.4f %.4f %.4f\\n", sqrt(2), exp(1), log(10), sin(1), cos(1), atan2(1, 1) }' },
  { p: 'BEGIN { print srand(5), srand(7) }' },
  { p: 'BEGIN { x = rand(); print (x >= 0 && x < 1) }' },
  { p: 'BEGIN { print length(x = "abc"), x }' },
  { p: 'BEGIN { print close("nothing"), fflush() }' },

  // Arrays
  { p: 'BEGIN { a["x"] = 1; print ("x" in a), ("y" in a), length(a) }' },
  { p: 'BEGIN { if (a["k"] == "") print ("k" in a) }' },
  { p: 'BEGIN { a[1,2] = 3; for (k in a) { split(k, p, SUBSEP); print p[1], p[2] }; print ((1,2) in a) }' },
  { p: 'BEGIN { a[1]; a[2]; delete a[1]; print length(a), (1 in a), (2 in a); delete a; print length(a) }' },
  { p: 'BEGIN { a[01] = "x"; print a[1], a["1"], a["01"] "|" }' },
  { p: 'BEGIN { a[0.1] = 1; for (k in a) print k }' },
  { p: '{ s += $2 } END { print s, s / NR }', in: table },
  { p: '{ n[$3]++ } END { print n["NY"], n["LA"], n["XX"] + 0 }', in: table },
  { p: '{ total[$3] += $2 } END { t = 0; for (k in total) t += total[k]; print t }', in: table },
  { p: '{ line[NR] = $0 } END { for (i = NR; i > 0; i--) print line[i] }', in: 'a\nb\nc\n' },
  { p: 'BEGIN { for (k in ENVIRON) n++; print (n > 0) }' },

  // Control flow
  { p: 'BEGIN { for (i = 1; i <= 3; i++) printf "%d ", i; print "" }' },
  { p: 'BEGIN { i = 0; while (i < 3) { i++; if (i == 2) continue; print i } }' },
  { p: 'BEGIN { i = 5; do { print i; i++ } while (i < 3) }' },
  { p: 'BEGIN { for (;;) { if (++n > 4) break }; print n }' },
  { p: 'BEGIN { for (i = 0; i < 3; i++) for (j = 0; j < 3; j++) { if (j == 1) break; print i, j } }' },
  { p: 'BEGIN { if (0) print "a"; else if (1) print "b"; else print "c" }' },
  { p: 'BEGIN { if (1)\n  print "multi"\nelse\n  print "no"\n}' },
  { p: 'BEGIN {\n  x = 1 +\n  2\n  print x\n}' },
  { p: 'BEGIN { x = 1 \\\n + 2; print x }' },
  { p: 'BEGIN { print "a",\n "b" }' },
  { p: 'BEGIN { a = 1; b = 0; if (a &&\n b) print "and"; else print "not" }' },
  { p: '# comment\nBEGIN { print "c" } # trailing\n# more' },
  { p: 'NR == 2 { next } { print }', in: '1\n2\n3\n' },
  { p: '{ print } NR == 2 { exit } END { print "end", NR }', in: '1\n2\n3\n' },
  { p: 'BEGIN { exit 3 } END { print "end" }' },
  { p: 'BEGIN { exit } END { print "end"; exit 4; print "no" }' },
  { p: 'END { exit NR }', in: 'a\nb\n' },
  { p: 'BEGIN { exit -1 }' },
  { p: 'BEGIN { while (1) { if (++i == 3) exit 7 } }' },

  // Functions
  { p: 'function fact(n) { return n <= 1 ? 1 : n * fact(n - 1) } BEGIN { print fact(10), fact(20) }' },
  { p: 'function fib(n) { return n < 2 ? n : fib(n-1) + fib(n-2) } BEGIN { print fib(18) }' },
  { p: 'function f(a) { a["x"] = 1 } BEGIN { f(arr); print length(arr), arr["x"] }' },
  { p: 'function f(s) { s = "changed"; return s } BEGIN { v = "orig"; r = f(v); print v, r }' },
  { p: 'function f(x,   local1) { local1 = x * 2; return local1 } BEGIN { print f(4), "[" local1 "]" }' },
  { p: 'function f() { return } BEGIN { x = f(); print "[" x "]", length(x) }' },
  { p: 'function g(a, i) { for (i in a) n++ ; return n } BEGIN { t[1]; t[2]; print g(t) }' },
  { p: 'function inc() { count++ } BEGIN { inc(); inc(); print count }' },
  { p: 'function f(a) { return a + 1 }\nBEGIN { print f(f(1)) }' },
  { p: 'function f(n) { if (n > 0) { print n; f(n - 1) } } BEGIN { f(3) }' },
  { p: 'function skip() { next } NR == 1 { skip() } { print }', in: 'a\nb\n' },
  { p: 'function bye() { exit 5 } { bye() } END { print "end" }', in: 'x\n' },
  { p: 'function add(arr, k) { arr[k] = k } BEGIN { add(t, "a"); add(t, "b"); print length(t), t["b"] }' },
  { p: 'func f() { return "func" } BEGIN { print f() }' },

  // getline
  { p: 'BEGIN { while ((getline line < "f1") > 0) n++; print n, line }', files: { f1: 'l1\nl2\nl3\n' } },
  { p: 'BEGIN { getline < "f1"; print $0, NF, NR }', files: { f1: 'a b c\n' } },
  { p: 'BEGIN { print (getline line < "missing") }' },
  { p: 'BEGIN { getline l < "f1"; close("f1"); getline m < "f1"; print l, m }', files: { f1: 'first\nsecond\n' } },
  { p: 'NR == 1 { getline; print "got", $0, NR } { print "rule", $0 }', in: '1\n2\n3\n' },
  { p: 'NR == 1 { getline x; print "x=" x, $0, NR }', in: '1\n2\n' },
  { p: '{ while ((getline) > 0) n++ } END { print n, NR }', in: 'a\nb\nc\n' },
  { p: 'BEGIN { while ((getline line) > 0) print "B:" line }', in: 'a\nb\n' },
  { p: 'BEGIN { print "one" > "out"; print "two" > "out"; close("out"); while ((getline l < "out") > 0) print "read", l }' },
  { p: 'BEGIN { print "a" > "out"; close("out"); print "b" >> "out"; close("out"); while ((getline l < "out") > 0) print l }' },

  // -v and assignments
  { args: ['-v', 'n=2'], p: 'NR <= n', in: 'a\nb\nc\n' },
  { args: ['-v', 'x=a\\tb'], p: 'BEGIN { print x, length(x) }' },
  { args: ['-v', 'x=10'], p: 'BEGIN { print (x < 9), (x == 10.0) }' },
  { args: ['-v', 'OFS=:', '-F', ','], p: '{ $1 = $1; print }', in: 'a,b\n' },

  // Regex details
  { p: '/^[[:digit:]]+$/', in: '12\n1a\n\n345\n' },
  { p: '/a|b/ { n++ } END { print n }', in: 'a\nc\nb\n' },
  { p: '/x{2,3}/', in: 'x\nxx\nxxxx\n' },
  { p: '$0 ~ "^a.c$"', in: 'abc\naXc\nac\n' },
  { p: '/[/]/', in: 'a/b\nab\n' },
  { p: '/a\\/b/', in: 'a/b\nab\n' },
  { p: '{ print ($0 ~ /\\./), ($0 ~ "\\\\.") }', in: 'a.b\nab\n' },
  { p: 'BEGIN { re = "b+"; s = "abbbc"; gsub(re, "X", s); print s }' },
  { p: '/\\t/', in: 'a\tb\nab\n' },
  { p: '{ print (/b/ ? "yes" : "no") }', in: 'abc\nxyz\n' },
  { p: '{ x = /b/; print x }', in: 'abc\nxyz\n' },
  { p: '{ print 10 / 2 / 5 }', in: 'x\n' },
  { p: '{ a = 6; print a /2/ 3 }', in: 'x\n' },

  // Programs people actually write
  { p: '{ $1 = ""; print substr($0, 2) }', in: table },
  { p: 'NF { print $NF }', in: 'a b\n\nc\n' },
  { p: '{ printf "%-10s %5.1f\\n", $1, $2 }', in: table },
  { p: 'BEGIN { FS = OFS = "\\t" } { print $2, $1 }', in: 'a\tb c\n' },
  { p: 'length($0) > max { max = length($0); line = $0 } END { print max, line }', in: table },
  { args: ['-F', '"'], p: '{ print $2 }', in: 'say "hello" now\n' },
  { p: String.raw`/^function/ { name = $2; sub(/\(.*/, "", name); print NR ": " name }`, in: 'x\nfunction foo(a, b)\nfunction bar()\n' },
  { p: 'BEGIN { while ((getline line < ARGV[1]) > 0) print "got " line }', ops: ['f1'], files: { f1: 'a\nb\n' } },
  { p: '{ print toupper(substr($0, 1, 1)) substr($0, 2) }', in: 'hello world\n' },
  { p: 'NR > 1 { print prev } { prev = $0 }', in: '1\n2\n3\n' },
  { p: '{ printf "%s%s", sep, $1; sep = "," } END { print "" }', in: table },
  { p: '$1 == "local" && $2 ~ /^[A-Z]/', in: 'local Foo = 1\nlocal bar = 2\nreturn Foo\n' },
  { p: '{ n = split($0, c, ""); for (i = n; i > 0; i--) printf "%s", c[i]; print "" }', in: 'abc\n' },
  { args: ['-v', 'OFS=,'], p: '{ $1 = $1 } 1', in: 'a b c\n' },
  { p: String.raw`{ gsub(/^[ \t]+|[ \t]+$/, ""); print "[" $0 "]" }`, in: '  a b  \n\tc\t\n' },
  { p: '{ print NR, NF, $0 }', ops: [String.raw`OFS=\t`, '-'], in: 'x y\n' },
  { p: '{ sub(/#.*/, "") } NF', in: 'code # note\n# only\n\nmore\n' },
  { args: ['-v', 'pat=a.c'], p: '$0 ~ pat', in: 'abc\nac\na.c\n' },
  { p: '{ print ($1 > $2 ? $1 : $2) }', in: '3 5\n9 2\n' },
  { p: '{ printf("%s|\\n", $0) > "out" } END { close("out"); while ((getline l < "out") > 0) print l }', in: 'a\nb\n' },
  { p: '{ print $1 }', ops: ['FS=,', 'f1'], files: { f1: 'a,b\n' } },
  { p: 'BEGIN { printf "%5.2f%%\\n", 12.345 }' },
  { p: '{ s = s (s ? "," : "") $1 } END { print s }', in: table },
  { p: 'NR == FNR { a[$1]; next } $1 in a', ops: ['f1', 'f2'], files: { f1: 'bob\ndave\n', f2: table } },
  { p: '{ $2 = sprintf("%05d", $2) } 1', in: table },
  { p: 'BEGIN { n = split("3,1,2", a, ","); for (i = 1; i <= n; i++) s += a[i]; print s / n }' },
  { p: '{ $0 = tolower($0) } /alice/', in: 'ALICE x\nbob\n' },
  { p: '{ c[$3]++ } END { for (k in c) if (c[k] > 1) print k }', in: table },
  { p: 'BEGIN { getline; print "first: " $0 } { print "rest: " $0 }', in: 'one\ntwo\n' },
  { p: 'END { print NR ? $0 : "empty" }', in: '' },

  // Errors: exit status 2, and output before a runtime error is kept
  { p: '{ print' },
  // A variable divisor: gawk folds `1/0` while parsing, which is not the runtime path.
  { p: 'BEGIN { z = 0; print 1/z }' },
  { p: '{ print } { print 1 % z }', in: 'kept\n' },
  { p: 'BEGIN { x = 1; x[1] = 2 }' },
  { p: 'BEGIN { a[1] = 1; print a }' },
  { p: 'BEGIN { undefined_fn() }' },
  { p: 'BEGIN { print $-1 }' },
  { p: 'BEGIN { getline < "missing"; print "still" }' },
  { p: '{ print }', ops: ['missing'] },
  { p: 'function f(a, a) { } BEGIN { }' },
  { p: 'BEGIN { next }' },
];
