// Pure language cases: no host filesystem/processes, locale-specific output,
// or harness-only diagnostic prose. Compare output and numeric exit status.
export default [
  'true; echo $?; false; echo $?',
  'false || true; echo $?; ! true; echo $?',
  'A=one; A=two true; echo "$A"',
  'A="x y"; printf "<%s>" $A; printf "<%s>" "$A"',
  'unset A; echo "${A:-default}"; echo "${A:=assigned}"; echo "$A"',
  'A=; echo "${A-default}:${A:-default}:${A+set}:${A:+set}"',
  'echo "$((1+2*3)) $((-7/2)) $((-7%2)) $((2**3**2)) $((-2**2))"',
  'echo "$((~0)) $((-8>>2)) $((1<<40)) $((-1&1099511627776))"',
  'echo "$((1 || 1/0)) $((0 && 1/0)) $((0 ? 1/0 : 9))"',
  'if false; then echo no; elif true; then echo yes; else echo no; fi',
  'if false; then :; fi; echo $?; until true; do :; done; echo $?',
  'i=0; until [ "$i" -eq 3 ]; do printf %s "$i"; i=$((i+1)); done',
  'i=0; while [ "$i" -lt 3 ]; do i=$((i+1)); [ "$i" -eq 2 ] && continue; echo "$i"; done',
  'for a in 1 2; do for b in x y; do echo "$a$b"; break 2; done; done',
  'case foobar in x*) echo no;; foo[ab]*|yes) echo yes;; *) echo no;; esac',
  'case "*" in "*") echo literal;; *) echo no;; esac',
  'echo a{b,c}{1,2} {03..01} {x..z}',
  'echo "$(printf \'a; b\\n\\n\')"; echo `echo inner`',
  'A=outer; echo "$(A=inner; echo "$A")"; echo "$A"',
  'f() { local A=inner; printf "%s:%s:%s" "$#" "$1" "$2"; }; A=outer; f "a b" c; echo "$A"',
  'f() { printf "<%s>" "$@"; }; f "a b" c ""',
  'f() { for arg; do printf "<%s>" "$arg"; done; }; f "a b" c',
  'f() { return 7; echo no; }; f; echo $?',
  '(A=inner; echo "$A"); echo "${A-unset}"',
  '{ printf a; printf b; }; printf c',
  'printf "a\\nb\\n" | while IFS= read -r line; do printf "[%s]" "$line"; done',
  'printf "a\\nb" | while IFS= read -r line || [ -n "$line" ]; do printf "[%s]" "$line"; done',
  'printf "  a   b c  \\n" | { read a b; printf "<%s><%s>" "$a" "$b"; }',
  'printf "%s\\n" "a\\ b c" | { read a b; printf "<%s><%s>" "$a" "$b"; }',
  'printf "%s\\n" "a\\ b c" | { read -r a b; printf "<%s><%s>" "$a" "$b"; }',
  'printf "a::b:c:\\n" | { IFS=: read a b c; printf "<%s><%s><%s>" "$a" "$b" "$c"; }',
  'printf "a:b:\\n" | { IFS=: read a b; printf "<%s><%s>" "$a" "$b"; }',
  'printf "a::\\n" | { IFS=: read a b; printf "<%s><%s>" "$a" "$b"; }',
  'printf "a:::  \\n" | { IFS=" :" read a b; printf "<%s><%s>" "$a" "$b"; }',
  'printf "  a : b : c  \\n" | { IFS=" :" read a b; printf "<%s><%s>" "$a" "$b"; }',
  'printf -v A "%04d" 7; echo "$A"',
  'printf -v A %d invalid 2>/dev/null; echo "$?:$A"',
  'A=$(false); echo $?; false; A=ok; echo $?',
  'false | true; echo $?; true | false; echo $?',
  'exit 7; echo no',
  '( exit 5 ); echo after=$?',
  '( exit 5 ) | cat; echo after=$?',
  'f() { echo a | { return 3; }; echo after; }; f; echo status=$?',
  'V=outer; f() { local V; echo "[${V-unset}]"; }; f; echo "$V"',
  'V=outer; f() { local V=in; ( local W=sub; echo "$V$W" ); }; f; echo "$V"',
  'f() { local V=in; echo x | { local W=y; echo "$V$W"; }; echo "[${W-unset}]"; }; f',
  'f() { local V=in; echo "$(local W=cs; echo "$V$W")"; }; f',
  '{ echo A; echo mid >&2; echo B; } 2>&1',
  '{ printf abc; printf err >&2; printf def; } 2>&1',
  '{ echo A; echo mid >&2; echo B; } 2>&1 | cat',
  '{ echo A; echo mid >&2; echo B; } 2>/dev/null',
  'for i in 1 2; do echo "out$i"; echo "err$i" >&2; done 2>&1',
  'if true; then echo A; echo mid >&2; echo B; fi 2>&1',
  '{ echo A; echo mid >&2; } 2>&1 | { read a; read b; echo "$b:$a"; }',
  'i=0; while [ $i -lt 2 ]; do i=$((i+1)); echo "o$i"; echo "e$i" >&2; done 2>&1',
  'i=5; echo "$((++i)) $i"; echo "$((i++)) $i"; echo "$((--i)) $i"; echo "$((i--)) $i"',
  'i=5; echo "$((i+=3)) $i"; echo "$((i*=2)) $i"; echo "$((i%=7)) $i"',
  'echo "$((n=4)) $n"; echo "$((n<<=2)) $n"; echo "$((n|=1)) $n"',
  'i=0; while [ $((i++)) -lt 3 ]; do printf %s "$i"; done',
  '{ printf BEFORE; X="$(echo mid >&2; echo out)"; printf "[%s]AFTER" "$X"; } 2>&1',
  'X="$(exit 3)"; echo "$?"',
];
